GET https://rose-penguin-cap.cyclic.app/api/persons/

###
GET http://localhost:3001/api/persons/

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Reimari",
    "number": 213123123
}

###
PUT http://localhost:3001/api/persons/Cirno
Content-Type: application/json

{
    "name": "Sirno",
    "number": 3242343
}