GET https://rose-penguin-cap.cyclic.app/api/persons/

###
GET http://localhost:3001/api/persons/

###

DELETE https://rose-penguin-cap.cyclic.app/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellasu",
    "number": 213123123
}